---
primaryNode:  
  nickname: Primary Master Node
  ipAddress: 192.168.1.81
  fqdn: k3smaster01.hellheim.info
  userId: nehemoth
  script: Primary-Master-Node-ip-89.sh 
  k3sToken: K105db82e39a8ec3a05de569a7a2e4ffdf2fa3c1db21f87fad5b22e764af61d0d96::server:e54cb4ab0d4026b645c8156477ac7220
otherMasterNodes:
- nickname: Second Master Node
  ipAddress: 192.168.1.82
  fqdn: k3smaster02.hellheim.info
  userId: nehemoth
  script: Second-Master-Node-ip-88.sh
workernodes:
- nickname: First Worker Node
  ipAddress: 192.168.1.83
  fqdn: k3sworker01.hellheim.info
  userId: nehemoth
  script: First-Worker-Node-ip-93.sh  
- nickname: Second Worker Node
  ipAddress: 192.168.1.84
  fqdn: k3sworker02.hellheim.info
  userId: nehemoth
  script: Second-Worker-Node-ip-95.sh  
- nickname: Third Worker Node
  ipAddress: 192.168.1.85
  fqdn: k3sworker03.hellheim.info
  userId: nehemoth
  script: Third-Worker-Node-ip-97.sh
targetFile: K3S_Auto_Cluster_Generator_Schedule.txt
