---
primaryNode:
  nickname: Primary Master Node
  ipAddress: 10.154.2.85
  userId: nickm
  k3sToken: K105db82e39a8ec3a05de569a7a2e4ffdf2fa3c1db21f87fad5b22e764af61d0d96::server:e54cb4ab0d4026b645c8156477ac7220
otherMasterNodes:
- nickname: Second Master Node
  ipAddress: 10.154.2.87
  userId: nickm
- nickname: Third Master Node
  ipAddress: 10.154.2.90
  userId: nickm
workernodes:
- nickname: First Worker Node
  ipAddress: 10.154.2.91
  userId: nickm
- nickname: Second Worker Node
  ipAddress: 10.154.2.92
  userId: nickm
- nickname: Third Worker Node
  ipAddress: 10.154.2.80
  userId: nickm
- nickname: Fourth Worker Node
  ipAddress: 10.154.2.81
  userId: nickm
targetFile: K3S_Auto_Cluster_Generator_Schedule.txt

