#! /bin/bash
# dummyscript
#######################
# dummynickname #
#######################
# IP Address: dummyipAddress
# FQDN: dummyfqdn
# User ID: dummyuserId
# Primary Master Node IP Address: 10.154.2.89
# K3s Token: K105db82e39a8ec3a05de569a7a2e4ffdf2fa3c1db21f87fad5b22e764af61d0d96::server:e54cb4ab0d4026b645c8156477ac7220
# 
k3s_token="K105db82e39a8ec3a05de569a7a2e4ffdf2fa3c1db21f87fad5b22e764af61d0d96::server:e54cb4ab0d4026b645c8156477ac7220"
k3s_url="https://10.154.2.89:6443"
node_name="dummyfqdn"
curl -sfL https://get.k3s.io | K3S_TOKEN=${k3s_token} K3S_NODE_NAME=${node_name} sh -s - server --server ${k3s_url}

